# Generated by Django 5.1.1 on 2025-03-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='not_accepted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Not Confirmed'), ('pending', 'Confirmed but Pending'), ('donated', 'Donated'), ('not_accepted', 'Not Accepted')], default='not_confirmed', max_length=20),
        ),
    ]
