# Generated by Django 5.1.1 on 2025-03-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_donation_bloodgroup_donation_not_accepted_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='bloodgroup',
        ),
    ]
