# Generated by Django 5.1.1 on 2025-03-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_donation_bloodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='confirmed',
        ),
    ]
