# Generated by Django 5.1.1 on 2025-03-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_donation_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
