# Generated by Django 5.1.1 on 2025-03-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('request_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('not_fulfilled', 'Not Fulfilled')], default='pending', max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_donation', to='main.bloodbank')),
            ],
        ),
    ]
