# Generated by Django 5.1.1 on 2025-03-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='sent_requests',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FulfilledRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfilled_requests', to='main.donationrequest')),
                ('users', models.ManyToManyField(related_name='fulfilled_requests', to='main.normaluser')),
            ],
        ),
    ]
