# Generated by Django 5.1.1 on 2025-03-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_fulfilledrequests_donation_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfilledrequests',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, related_name='fulfilled_requests', to='main.normaluser'),
        ),
    ]
