# Generated by Django 5.1.1 on 2025-03-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_fulfilledrequests_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulfilledrequests',
            old_name='donation_request',
            new_name='donation_req_id',
        ),
    ]
