# Generated by Django 5.1.1 on 2025-03-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_donation_request_fulfilledrequests_donation_req_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfilledrequests',
            name='users',
        ),
        migrations.AddField(
            model_name='fulfilledrequests',
            name='user_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of user IDs', null=True),
        ),
    ]
