# Generated by Django 5.1.1 on 2025-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_fulfilledrequests_fulfilled_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfilledrequests',
            name='fulfilled_by',
        ),
        migrations.RemoveField(
            model_name='fulfilledrequests',
            name='user_ids',
        ),
        migrations.AddField(
            model_name='fulfilledrequests',
            name='user_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of user IDs', null=True),
        ),
    ]
