# Generated by Django 5.1.1 on 2025-03-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_fulfilledrequests_fulfilled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfilledrequests',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfilled_donations', to='main.normaluser'),
        ),
        migrations.RemoveField(
            model_name='fulfilledrequests',
            name='user_ids',
        ),
        migrations.AddField(
            model_name='fulfilledrequests',
            name='user_ids',
            field=models.ManyToManyField(blank=True, related_name='participated_fulfillments', to='main.normaluser'),
        ),
    ]
