# Generated by Django 5.1.1 on 2025-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_fulfilledrequests_fulfilled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loc_latitude',
            field=models.DecimalField(decimal_places=7, default=19.1674517, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loc_longitude',
            field=models.DecimalField(decimal_places=7, default=72.8513831, max_digits=10),
        ),
    ]
