# Generated by Django 5.1.1 on 2025-03-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_bloodbank_max_capacity_per_group_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
