# Generated by Django 5.1.1 on 2025-03-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='a0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='a1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='ab0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='ab1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='b0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='b1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='o0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='o1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
