# Generated by Django 5.1.1 on 2025-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_bloodbank_a0_bloodbank_a1_bloodbank_ab0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
