# Generated by Django 5.1.1 on 2025-04-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_bloodbank_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='website',
            field=models.URLField(default='https://example.com'),
        ),
    ]
